# A SHA256 hash of the instance secret is the "admin" api key
instanceSecret: "secret-value-shared-by-all-nodes"
rootPrefix: "some-secure-prefix"

# If first time launch, non-leaders will auto-follow this leader
defaultLeader: "node0"

# Directory for storing insi data
insiHome: "/Users/bosley/.config/insi"

# TLS will be in same spot on all nodes
tls:
  cert: /Users/bosley/.config/insi/keys/server.crt
  key: /Users/bosley/.config/insi/keys/server.key

clientSkipVerify: true
serverMustUseTLS: true

trustedProxies:
  - "127.0.0.1"
  - "::1"

permittedIPs:
  - "127.0.0.1"
  - "::1"
  - "*"  # Permitting `*` is permitted, but internally IGNORED on "private" routes (admin/ internal/ etc)

cache:
  standard-ttl: 60m
  keys: 1m

rateLimiters:
  default: 
    limit: 5
    burst: 10
  values:
    limit: 1000
    burst: 1500 
  cache:
    limit: 1000
    burst: 1500
  system:
    limit: 10
    burst: 15
  events:
    limit: 1000
    burst: 1500

sessions:
  eventChannelSize: 256
  webSocketReadBufferSize: 1024
  webSocketWriteBufferSize: 1024
  maxConnections: 1000

nodes:
  node0:
    raftBinding: 127.0.0.1:2222
    privateBinding: 127.0.0.1:8446
    publicBinding: 127.0.0.1:8443
    clientDomain: "localhost"
    nodeSecret: "node0-secret"
  node1:
    raftBinding: 127.0.0.1:2223
    privateBinding: 127.0.0.1:8447
    publicBinding: 127.0.0.1:8444
    clientDomain: "localhost"
    nodeSecret: "node1-secret"
  node2:
    raftBinding: 127.0.0.1:2224
    privateBinding: 127.0.0.1:8448
    publicBinding: 127.0.0.1:8445
    clientDomain: "localhost"
    nodeSecret: "node2-secret"

logging:
  level: "info"