prod: false

domain: "localhost" # defaults to localhost if not provided
url: "http://example.com" # defaults to https://<domain>
port: 8080 # defaults to 8080 if not provided

https: true

# Ignored if https is false
key_path: /Users/bosley/.config/insi/keys/server.key
cert_path: /Users/bosley/.config/insi/keys/server.crt

secret: "some-web-app-secret"

admin_emails:
  - "admin@example.com"

permitted_ips: # can be used to restrict access to the web app (all requests must come from an ip in this list)
  - "127.0.0.1"
  - "::1"
  - "*"

trusted_proxies: # can be used to trust proxies (all requests must come from a proxy in this list [if app is in cluster mode and is auto balancing])
  - "127.0.0.1"
  - "::1"
  - "*"

# Web cache/rate limiting settings
cache:
  standard_ttl: 60m
  keys: 1m

rate_limiters:
  default:
    limit: 5
    burst: 10
  authorized_users:
    limit: 100
    burst: 150